force-app/main/default/objects/SCH_Schedule_Action__c/SCH_Schedule_Action__c.object-meta.xml
<CustomObject>
    <label>Schedule Action</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SCH_Schedule_Action__c/fields/Associate_With_Referenced_Record__c.field-meta.xml
<CustomField>
    <fullName>Associate_With_Referenced_Record__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Associate Activity With Referenced Rec?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SCH_Schedule_Action__c/fields/Email_From_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_From_Address__c</fullName>
    <label>Email From Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/SCH_Schedule_Action__c/fields/Email_From_Address_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_From_Address_Id__c</fullName>
    <label>Email From Address Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCH_Schedule_Action__c/fields/Email_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Id__c</fullName>
    <label>Email Template Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/force-app/main/default/objects/SCH_Schedule_Action__c/fields/Email_To_Address_Field__c.field-meta.xml
<CustomField>
    <fullName>Email_To_Address_Field__c</fullName>
    <label>Email To Address Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCH_Schedule_Action__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <label>Schedule</label>
    <referenceTo>SCH_Schedule__c</referenceTo>
    <relationshipLabel>Schedule Actions</relationshipLabel>
    <relationshipName>Schedule_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/force-app/main/default/objects/SCH_Schedule_Action__c/fields/SMS_Attachment_Id__c.field-meta.xml
<CustomField>
    <fullName>SMS_Attachment_Id__c</fullName>
    <label>SMS Attachment Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCH_Schedule_Action__c/fields/SMS_From_Number__c.field-meta.xml
<CustomField>
    <fullName>SMS_From_Number__c</fullName>
    <label>SMS From Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/force-app/main/default/objects/SCH_Schedule_Action__c/fields/SMS_Message__c.field-meta.xml
<CustomField>
    <fullName>SMS_Message__c</fullName>
    <label>SMS Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SCH_Schedule_Action__c/fields/SMS_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>SMS_Template_Id__c</fullName>
    <label>SMS Template Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCH_Schedule_Action__c/fields/SMS_To_Number_Field__c.field-meta.xml
<CustomField>
    <fullName>SMS_To_Number_Field__c</fullName>
    <label>SMS To Number Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SCH_ScheduleActionSelector.cls
/**
 * Blackthorn.io, Inc CONFIDENTIAL
 * __________________________________
 * 
 *  [2022] Blackthorn.io, Inc
 *  All Rights Reserved.
 * 
 * NOTICE:  All information contained herein is, and remains
 * the property of Blackthorn.io, Inc and its suppliers,
 * if any. The intellectual and technical concepts contained
 * herein are proprietary to Blackthorn.io, Inc
 * and its suppliers and may be covered by U.S. and Foreign Patents,
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Blackthorn.io, Inc.
 *
 * 
 * The Selector class for the Schedule Action sObject
 *
**/
public with sharing class SCH_ScheduleActionSelector extends fflib_SObjectSelector {

	/**
	 *  @return a List of Schema.SObjectFields
	 *
	 *  Return a List of Schema.SObjectFields for this object.
	 *
	 **/
	public List<Schema.SObjectField> getSObjectFieldList() {
		return new List<Schema.SObjectField> {
			SCH_Schedule_Action__c.Id,
			SCH_Schedule_Action__c.Action__c,
			SCH_Schedule_Action__c.Name,
			SCH_Schedule_Action__c.Email_From_Address__c,
			SCH_Schedule_Action__c.Email_From_Address_Id__c,
			SCH_Schedule_Action__c.Email_To_Address_Field__c,
			SCH_Schedule_Action__c.Email_Template_Id__c,
			SCH_Schedule_Action__c.SMS_From_Number__c,
			SCH_Schedule_Action__c.SMS_To_Number_Field__c,
			SCH_Schedule_Action__c.Schedule__c,
			SCH_Schedule_Action__c.SMS_Message__c,
			SCH_Schedule_Action__c.SMS_Template_Id__c,
			SCH_Schedule_Action__c.SMS_Attachment_Id__c,
			SCH_Schedule_Action__c.Associate_With_Referenced_Record__c
		};
	}

	/**
	 *  @return a Schema.SObjectType
	 *
	 *  Return the SObjectType for this object.
	 *
	 **/
	public Schema.SObjectType getSObjectType() {
		return SCH_Schedule_Action__c.sObjectType;
	}

}