force-app/force-app/main/default/objects/Form_Submission__c/Form_Submission__c.object-meta.xml
<CustomObject>
    <description>Submissions from forms or custom questions related to Blackthorn apps.</description>
    <label>BT Form Submission</label>
    <nameField>
        <displayFormat>FS-{000000}</displayFormat>
        <label>Form Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT Form Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Submission_Answer__c/Form_Submission_Answer__c.object-meta.xml
<CustomObject>
    <description>Each submitted form answer is saved here.</description>
    <label>BT Form Submission Answer</label>
    <nameField>
        <displayFormat>FSA-{000000}</displayFormat>
        <label>Form Submission Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT Form Submission Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/force-app/main/default/objects/Form_Submission_Answer__c/fields/Form_Submission__c.field-meta.xml
<CustomField>
    <fullName>Form_Submission__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The originating Form Submission.</description>
    <inlineHelpText>The originating Form Submission.</inlineHelpText>
    <label>Form Submission</label>
    <referenceTo>Form_Submission__c</referenceTo>
    <relationshipLabel>Form Submission Answers</relationshipLabel>
    <relationshipName>Form_Submission_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/force-app/main/default/classes/FormSubmissionAnswerSelectorTest.cls
@IsTest
private class FormSubmissionAnswerSelectorTest {
    @IsTest
    private static void testGetSObjectFieldList_expectFieldList() {
        Test.startTest();
            System.assertNotEquals(0, new FormSubmissionAnswerSelector().getSObjectFieldList().size(), 'Field list is returned from the selector');
        Test.stopTest();
    }

    @IsTest
    private static void testGetSObjectType_expectFormElementObject() {
        Test.startTest();
            System.assertEquals(Form_Submission_Answer__c.SObjectType, new FormSubmissionAnswerSelector().getSObjectType(), 'It return Form_Submission_Answer__c schema type');
        Test.stopTest();
    }

    @IsTest
    private static void testGetAnswerByFormSubmissionId_expectRecordsReturned() {
        
        Form_Submission__c submission = new Form_Submission__c(Key__c= 'abcdefg');
        insert submission;

        Form_Submission_Answer__c answer = new Form_Submission_Answer__c( Form_Submission__c = submission.Id);
        insert answer;

        Test.startTest();
            List<Form_Submission_Answer__c> recordList = new FormSubmissionAnswerSelector().getAnswerByFormSubmissionId(new Set<Id> { submission.Id });
            
        Test.stopTest();
        System.assertEquals(1, recordList.size(), 'Only one record should be returned as we passed 1 id');
        System.assertEquals(answer.Id, recordList[0].Id, 'Id needs to match the id which we passed');
    }

    @IsTest
    private static void testGetAnswerByFormSubmissionId_expectNoRecordsReturned() {
        
        Form_Submission__c submission = new Form_Submission__c(Key__c= 'abcdefg');
        insert submission;

        Test.startTest();
            List<Form_Submission_Answer__c> recordList = new FormSubmissionAnswerSelector().getAnswerByFormSubmissionId(new Set<Id> { Helpers.getFakeId(Form_Submission_Answer__c.SObjectType) });
            
        Test.stopTest();
        System.assertEquals(0, recordList.size(), 'No record should be returned as we passed wrong key');
    }

    @IsTest
    private static void testSelectSObjectsById_expectRecordsReturned() {
        
        Form_Submission__c submission = new Form_Submission__c(Key__c= 'abcdefg');
        insert submission;

        Form_Submission_Answer__c answer = new Form_Submission_Answer__c( Form_Submission__c = submission.Id);
        insert answer;

        Test.startTest();
            List<Form_Submission_Answer__c> recordList = new FormSubmissionAnswerSelector().selectSObjectsById(new Set<Id> { answer.Id });
            
        Test.stopTest();
        System.assertEquals(1, recordList.size(), 'Only one record should be returned as we passed 1 id');
        System.assertEquals(answer.Id, recordList[0].Id, 'Id needs to match the id which we passed');
    }

    @IsTest
    private static void testSelectSObjectsById_expectNoRecordsReturned() {
        Test.startTest();
            List<Form_Submission_Answer__c> recordList = new FormSubmissionAnswerSelector().selectSObjectsById(new Set<Id> { Helpers.getFakeId(Form_Submission_Answer__c.SObjectType) });
            
        Test.stopTest();
        System.assertEquals(0, recordList.size(), 'no record should be returned as we passed invalid id');
    }
}