force-app/force-app/main/default/objects/Form_Big_List_Group__c/Form_Big_List_Group__c.object-meta.xml
<CustomObject>
    <description>This is used to group Form Big List Option records together to be used in a Form Element (question). This can be used if you have a picklist or type ahead custom question that has more than 1,000 possible options.</description>
    <label>BT Form Big List Group</label>
    <nameField>
        <label>Form Big List Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BT Form Big List Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Element__c/Form_Element__c.object-meta.xml
<CustomObject>
    <description>Questions or other types of controls as part of a Form.</description>
    <label>BT Form Element</label>
    <nameField>
        <displayFormat>FE-{000000}</displayFormat>
        <label>Form Element Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT Form Elements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Element__c/fields/Form_Big_List_Group__c.field-meta.xml
<CustomField>
    <fullName>Form_Big_List_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If this Form Element references a Big List Group.</description>
    <inlineHelpText>If this Form Element references a Big List Group.</inlineHelpText>
    <label>Form Big List Group</label>
    <referenceTo>Form_Big_List_Group__c</referenceTo>
    <relationshipLabel>Form Elements</relationshipLabel>
    <relationshipName>Form_Elements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Element_Condition__c/Form_Element_Condition__c.object-meta.xml
<CustomObject>
    <description>Used for Form Elements with conditional logic.</description>
    <label>BT Form Element Condition</label>
    <nameField>
        <displayFormat>FEC-{000000}</displayFormat>
        <label>Form Element Condition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT Form Element Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Element_Condition__c/fields/Form_Element__c.field-meta.xml
<CustomField>
    <fullName>Form_Element__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The controlling Form Element.</description>
    <inlineHelpText>The controlling Form Element.</inlineHelpText>
    <label>Form Element</label>
    <referenceTo>Form_Element__c</referenceTo>
    <relationshipLabel>Form Element Conditions</relationshipLabel>
    <relationshipName>Form_Element_Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/force-app/main/default/objects/Form_Element_Condition__c/fields/Next_Form_Element__c.field-meta.xml
<CustomField>
    <fullName>Next_Form_Element__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Form Element that will follow if this Element&apos;s conditions are met.</description>
    <inlineHelpText>The Form Element that will follow if this Element&apos;s conditions are met.</inlineHelpText>
    <label>Next Form Element</label>
    <referenceTo>Form_Element__c</referenceTo>
    <relationshipLabel>Form Element Conditions (Next Form Element)</relationshipLabel>
    <relationshipName>Form_Element_Conditions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/force-app/main/default/classes/FormController.cls
public with sharing class FormController {
    public static Integer MAX_LIMIT = 10000;

    public class FormElementAndConditions {
        @AuraEnabled
        public Form_Element__c element { get; set; }
        @AuraEnabled
        public List<Form_Element_Condition__c> conditions { get; set; }
    }

    @AuraEnabled(cacheable=true)
    public static List<Form_Element__c> loadFormElements(Id formId) {
        FormElementSelector selector = new FormElementSelector();
        return selector.getElementsByFormId(formId, 2000);
    }

    @AuraEnabled(cacheable=true)
    public static List<Form_Element_Condition__c> loadFormElementConditions(Id formId) {
        FormElementConditionSelector selector = new FormElementConditionSelector();
        return selector.getConditionsByFormId(formId, 2000);
    }

    @AuraEnabled(cacheable=true)
    public static List<Form_Big_List_Group__c> loadBigListGroups() {
        FormBigListGroupSelector selector = new FormBigListGroupSelector();
        return selector.getBigListGroups(2000);
    }

    @AuraEnabled(cacheable=true)
    public static List<MapToList> listMapToObjects() {
        List<Form_Question_Map_To_Object__mdt> mcs = Form_Question_Map_To_Object__mdt.getAll().values();
        List<MapToList> mapToObjects = new List<MapToList>();
        for(Form_Question_Map_To_Object__mdt mc : mcs) {
            mapToObjects.add(new MapToList(mc.label, mc.Object_API_Name__c));
        }
        return mapToObjects;
    }

    @AuraEnabled
    public static FormElementAndConditions saveElementAndConditions(
        Form_Element__c element,
        List<Form_Element_Condition__c> conditions,
        List<Form_Element_Condition__c> conditionsToRemove
    ) {
        if (conditions.size() + conditionsToRemove.size() + 1 > MAX_LIMIT) {
            Helpers.errorMsgLightning(System.label.Form_Builder_Max_Limit);
        }
        if (String.isBlank(element.Id) || element.getPopulatedFieldsAsMap().size() > 1) {
            // The element need to be created or updated
            upsert element;
        }
        if (conditions.size() > 0) {
            for (Form_Element_Condition__c condition : conditions) {
                condition.Next_Form_Element__c = element.Id;
            }
            upsert conditions;
        }
        if (conditionsToRemove.size() > 0) {
            delete conditionsToRemove;
        }

        FormElementSelector elementSelector = new FormElementSelector();
        Form_Element__c freshElement = elementSelector.selectById(element.Id);
        FormElementConditionSelector conditionSelector = new FormElementConditionSelector();
        List<Form_Element_Condition__c> freshConditions = conditionSelector.getConditionsByControlledElement(
            freshElement,
            2000
        );
        FormElementAndConditions ec = new FormElementAndConditions();
        ec.element = freshElement;
        ec.conditions = freshConditions;
        return ec;
    }

    @AuraEnabled
    public static void saveFormElements(List<Form_Element__c> elements) {
        if (elements.size() > MAX_LIMIT) {
            Helpers.errorMsgLightning(System.label.Form_Builder_Max_Limit);
        } else if (elements.size() > 0) {
            upsert elements;
        }
    }

    @AuraEnabled
    public static void deleteFormElements(List<Form_Element__c> elements) {
        if (elements.size() > MAX_LIMIT) {
            Helpers.errorMsgLightning(System.label.Form_Builder_Max_Limit);
        } else if (elements.size() > 0) {
            delete elements;
        }
    }


    public class MapToList {
        @AuraEnabled
        public String label { get; set; }
        @AuraEnabled
        public String value { get; set; }

        public MapToList(String label, String value) {
            this.label = label;
            this.value = value;
        }
    }
}