force-app/force-app/main/default/objects/Branding_Setting__c/Branding_Setting__c.object-meta.xml
<CustomObject>
    <label>Branding Setting</label>
    <nameField>
        <label>Branding Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branding Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/force-app/main/default/objects/Branding_Setting__c/fields/Custom_CSS_URL__c.field-meta.xml
<CustomField>
    <fullName>Custom_CSS_URL__c</fullName>
    <inlineHelpText>A link to a custom CSS file for your Store.</inlineHelpText>
    <label>Custom CSS URL</label>
    <type>Url</type>
</CustomField>

force-app/force-app/main/default/objects/Branding_Setting__c/fields/Custom_Label_1__c.field-meta.xml
<CustomField>
    <fullName>Custom_Label_1__c</fullName>
    <inlineHelpText>Label for &quot;Custom URL 1&quot;. Displayed in the Store&apos;s footer.</inlineHelpText>
    <label>Custom Label 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/force-app/main/default/objects/Branding_Setting__c/fields/Custom_Label_2__c.field-meta.xml
<CustomField>
    <fullName>Custom_Label_2__c</fullName>
    <inlineHelpText>Label for &quot;Custom URL 2&quot;. Displayed in the Store&apos;s footer.</inlineHelpText>
    <label>Custom Label 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/force-app/main/default/objects/Branding_Setting__c/fields/Custom_Label_3__c.field-meta.xml
<CustomField>
    <fullName>Custom_Label_3__c</fullName>
    <inlineHelpText>Label for &quot;Custom URL 3&quot;. Displayed in the Store&apos;s footer.</inlineHelpText>
    <label>Custom Label 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branding_Setting__c/fields/Custom_Label_4__c.field-meta.xml
<CustomField>
    <fullName>Custom_Label_4__c</fullName>
    <inlineHelpText>Label for &quot;Custom URL 4&quot;. Displayed in the Store&apos;s footer.</inlineHelpText>
    <label>Custom Label 4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branding_Setting__c/fields/Custom_URL_1__c.field-meta.xml
<CustomField>
    <fullName>Custom_URL_1__c</fullName>
    <inlineHelpText>Custom URL to be displayed in your Store&apos;s footer. Can be a link to your website, GDPR notification, etc.</inlineHelpText>
    <label>Custom URL 1</label>
    <type>Url</type>
</CustomField>

force-app/force-app/main/default/objects/Branding_Setting__c/fields/Custom_URL_2__c.field-meta.xml
<CustomField>
    <fullName>Custom_URL_2__c</fullName>
    <inlineHelpText>Custom URL to be displayed in your Store&apos;s footer. Can be a link to your website, GDPR notification, etc.</inlineHelpText>
    <label>Custom URL 2</label>
    <type>Url</type>
</CustomField>

force-app/force-app/main/default/objects/Branding_Setting__c/fields/Custom_URL_3__c.field-meta.xml
<CustomField>
    <fullName>Custom_URL_3__c</fullName>
    <inlineHelpText>Custom URL to be displayed in your Store&apos;s footer. Can be a link to your website, GDPR notification, etc.</inlineHelpText>
    <label>Custom URL 3</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Branding_Setting__c/fields/Custom_URL_4__c.field-meta.xml
<CustomField>
    <fullName>Custom_URL_4__c</fullName>
    <inlineHelpText>Custom URL to be displayed in your Store&apos;s footer. Can be a link to your website, GDPR notification, etc.</inlineHelpText>
    <label>Custom URL 4</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Branding_Setting__c/fields/Logo_URL__c.field-meta.xml
<CustomField>
    <fullName>Logo_URL__c</fullName>
    <inlineHelpText>Enter a link to your logo to have it displayed on your Store.</inlineHelpText>
    <label>Logo URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Branding_Setting__c/fields/Primary_Color__c.field-meta.xml
<CustomField>
    <fullName>Primary_Color__c</fullName>
    <inlineHelpText>Primary color for your Store. Enter as a hex code without the #. Ex: Blackthorn blue would be 235EA4</inlineHelpText>
    <label>Primary Color</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branding_Setting__c/fields/Secondary_Color_Background_Color__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Color_Background_Color__c</fullName>
    <inlineHelpText>Secondary/background color for your Store. Enter as a hex code without the #. Ex: Blackthorn green would be 3A9E47</inlineHelpText>
    <label>Secondary Color Background Color</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/force-app/main/default/objects/Branding_Setting__c/fields/Theme__c.field-meta.xml
<CustomField>
    <fullName>Theme__c</fullName>
    <label>Theme</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Light</fullName>
                <default>true</default>
                <label>Light</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/force-app/main/default/classes/BrandingSettingSelector.cls
public with sharing class BrandingSettingSelector extends fflib_SObjectSelector {
	public List<Schema.SObjectField> getSObjectFieldList()
	{
		return new List<Schema.SObjectField> {
			Branding_Setting__c.Id,
			Branding_Setting__c.Name,
			Branding_Setting__c.Custom_CSS_URL__c,
			Branding_Setting__c.Custom_Label_1__c,
			Branding_Setting__c.Custom_Label_2__c,
			Branding_Setting__c.Custom_Label_3__c,
			Branding_Setting__c.Custom_Label_4__c,
			Branding_Setting__c.Custom_URL_1__c,
			Branding_Setting__c.Custom_URL_2__c,
			Branding_Setting__c.Custom_URL_3__c,
			Branding_Setting__c.Custom_URL_4__c,
			Branding_Setting__c.Default__c,
			Branding_Setting__c.Logo_URL__c,
			Branding_Setting__c.Primary_Color__c,
			Branding_Setting__c.Secondary_Color_Background_Color__c,
			Branding_Setting__c.Theme__c
		};
	}
	public List<Branding_Setting__c> getDefaultBrandingSettings() {
		assertIsAccessible();
		fflib_QueryFactory query = newQueryFactory();
		query.setCondition('Default__c = TRUE');
		return (List<Branding_Setting__c>) Database.query(query.toSOQL());
	}
	public Schema.SObjectType getSObjectType() {
		return Branding_Setting__c.SObjectType;
	}
}