force-app/force-app/main/default/objects/Branding_Setting__c/Branding_Setting__c.object-meta.xml
<CustomObject>
    <label>Branding Setting</label>
    <nameField>
        <label>Branding Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branding Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Branding_Setting__c/fields/Logo_URL__c.field-meta.xml
<CustomField>
    <fullName>Logo_URL__c</fullName>
    <inlineHelpText>Enter a link to your logo to have it displayed on your Store.</inlineHelpText>
    <label>Logo URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Branding_Setting__c/fields/Primary_Color__c.field-meta.xml
<CustomField>
    <fullName>Primary_Color__c</fullName>
    <inlineHelpText>Primary color for your Store. Enter as a hex code without the #. Ex: Blackthorn blue would be 235EA4</inlineHelpText>
    <label>Primary Color</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branding_Setting__c/fields/Secondary_Color_Background_Color__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Color_Background_Color__c</fullName>
    <inlineHelpText>Secondary/background color for your Store. Enter as a hex code without the #. Ex: Blackthorn green would be 3A9E47</inlineHelpText>
    <label>Secondary Color Background Color</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/force-app/main/default/objects/Branding_Setting__c/fields/Theme__c.field-meta.xml
<CustomField>
    <fullName>Theme__c</fullName>
    <label>Theme</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Light</fullName>
                <default>true</default>
                <label>Light</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/force-app/main/default/classes/BrandingSettingFFHandlerTest.cls
@IsTest
public with sharing class BrandingSettingFFHandlerTest {
	@IsTest
	static void checkDefaultBrandingSettingTest(){
		Boolean recordUpdated = true;
		Branding_Setting__c branding = new Branding_Setting__c();
		branding.Name = 'Branding Setting Test 2';
		branding.Primary_Color__c = 'Blue';
		branding.Secondary_Color_Background_Color__c = 'Red';
		branding.Logo_URL__c = 'https://google.com';
		branding.Theme__c = 'Light';
		branding.Default__c = true;
		insert branding;
		Branding_Setting__c branding2 = new Branding_Setting__c();
		branding2.Name = 'Branding Setting Test 2';
		branding2.Primary_Color__c = 'Blue';
		branding2.Secondary_Color_Background_Color__c = 'Red';
		branding2.Logo_URL__c = 'https://google.com';
		branding2.Theme__c = 'Light';
		branding2.Default__c = true;
		try {
			insert branding2;
			recordUpdated = true;
		} catch (Exception ex) {
			recordUpdated = false;
			System.assertEquals(true, ex.getMessage().contains(System.Label.Only_One_Default_Branding_Setting));
		}
		System.assertEquals(false, recordUpdated);
		branding2.Default__c = false;
		insert branding2;

		branding2.Default__c = true;
		Test.startTest();
		try {
			update branding2;
			recordUpdated = true;
		} catch (Exception ex) {
			recordUpdated = false;
			System.assertEquals(true, ex.getMessage().contains(System.Label.Only_One_Default_Branding_Setting));
		}
		Test.stopTest();
		System.assertEquals(false, recordUpdated);
	}
}