force-app/force-app/main/default/objects/Form__c/Form__c.object-meta.xml
<CustomObject>
    <description>Create sets of custom questions.</description>
    <label>BT Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BT Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Element__c/Form_Element__c.object-meta.xml
<CustomObject>
    <description>Questions or other types of controls as part of a Form.</description>
    <label>BT Form Element</label>
    <nameField>
        <displayFormat>FE-{000000}</displayFormat>
        <label>Form Element Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT Form Elements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/force-app/main/default/objects/Form_Element__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Form related to this Form Element.</description>
    <inlineHelpText>The Form related to this Form Element.</inlineHelpText>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Form Elements</relationshipLabel>
    <relationshipName>Form_Elements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Element__c/fields/Maps_To_Field__c.field-meta.xml
<CustomField>
    <fullName>Maps_To_Field__c</fullName>
    <description>This Form Element&apos;s answer should map to this field.</description>
    <inlineHelpText>This Form Element&apos;s answer should map to this field.</inlineHelpText>
    <label>Maps To (Field)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/force-app/main/default/objects/Form_Element__c/fields/Maps_To_Object__c.field-meta.xml
<CustomField>
    <fullName>Maps_To_Object__c</fullName>
    <description>This Form Element&apos;s answer should map to this object.</description>
    <inlineHelpText>This Form Element&apos;s answer should map to this object.</inlineHelpText>
    <label>Maps To (Object)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/force-app/main/default/objects/Form_Element__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description>The question of this Form Element.</description>
    <inlineHelpText>The question of this Form Element.</inlineHelpText>
    <label>Question</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/force-app/main/default/objects/Form_Element__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of question or element.</description>
    <inlineHelpText>The type of question or element.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Big List Group</fullName>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Divider</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>File Upload</fullName>
            </value>
            <value>
                <fullName>Hidden</fullName>
            </value>
            <value>
                <fullName>Multi-Select Picklist</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Parameter</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Text (30,000)</fullName>
            </value>
            <value>
                <fullName>URL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_Element_Condition__c/Form_Element_Condition__c.object-meta.xml
<CustomObject>
    <description>Used for Form Elements with conditional logic.</description>
    <label>BT Form Element Condition</label>
    <nameField>
        <displayFormat>FEC-{000000}</displayFormat>
        <label>Form Element Condition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT Form Element Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Element_Condition__c/fields/Condition_Operator__c.field-meta.xml
<CustomField>
    <fullName>Condition_Operator__c</fullName>
    <description>The operator by which this condition is evaluated.</description>
    <inlineHelpText>The operator by which this condition is evaluated.</inlineHelpText>
    <label>Condition Operator</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contains</fullName>
            </value>
            <value>
                <fullName>Equals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/force-app/main/default/objects/Form_Element_Condition__c/fields/Condition_Value__c.field-meta.xml
<CustomField>
    <fullName>Condition_Value__c</fullName>
    <description>The value used to evaluate this condition.</description>
    <inlineHelpText>The value used to evaluate this condition.</inlineHelpText>
    <label>Condition Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Element_Condition__c/fields/Form_Element__c.field-meta.xml
<CustomField>
    <fullName>Form_Element__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The controlling Form Element.</description>
    <inlineHelpText>The controlling Form Element.</inlineHelpText>
    <label>Form Element</label>
    <referenceTo>Form_Element__c</referenceTo>
    <relationshipLabel>Form Element Conditions</relationshipLabel>
    <relationshipName>Form_Element_Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/force-app/main/default/objects/Form_Element_Condition__c/fields/Next_Form_Element__c.field-meta.xml
<CustomField>
    <fullName>Next_Form_Element__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Form Element that will follow if this Element&apos;s conditions are met.</description>
    <inlineHelpText>The Form Element that will follow if this Element&apos;s conditions are met.</inlineHelpText>
    <label>Next Form Element</label>
    <referenceTo>Form_Element__c</referenceTo>
    <relationshipLabel>Form Element Conditions (Next Form Element)</relationshipLabel>
    <relationshipName>Form_Element_Conditions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FormTestDataHelper.cls
/**
 * Create the test data needed for the form tests
 */
public with sharing class FormTestDataHelper {
    public static Form_Element__c fe1, fe2;
    public static Form__c f1;
    public static Form_Element_Condition__c fec1, fec2;

    /**
     * Create a form for testing
     */
    public static void createForm() {
        f1 = new Form__c(Name = 'Contact');
        insert new List<Form__c>{ f1 };
    }

    /**
     * Create a form with elements for testing
     */
    public static void createFormWithElements() {
        createForm();

        fe1 = new Form_Element__c(
            Form__c = f1.Id,
            Question__c = 'Where is Spiderman?',
            Type__c = 'Text',
            Maps_To_Object__c = 'Contact',
            Maps_To_Field__c = 'FirstName'
        );

        fe2 = new Form_Element__c(
            Form__c = f1.Id,
            Question__c = 'When did the Berlin Wall fall?',
            Type__c = 'Date',
            Maps_To_Object__c = 'Contact',
            Maps_To_Field__c = 'LastName'
        );
        insert new List<Form_Element__c>{ fe1, fe2 };
    }

    /**
     * Create conditions for the form elements for testing 
    */
    public static void setupConditions() {
        fec1 = new Form_Element_Condition__c(
            Form_Element__c = fe1.Id,
            Condition_Operator__c = 'Equals',
            Condition_Value__c = 'Peter Parker',
            Next_Form_Element__c = fe2.Id
        );

        fec2 = new Form_Element_Condition__c(
            Form_Element__c = fe2.Id,
            Condition_Operator__c = 'Equals',
            Condition_Value__c = '1989-11-09',
            Next_Form_Element__c = fe1.Id
        );
        insert new List<Form_Element_Condition__c>{ fec1, fec2 };
    }

    /**
     * @description  This method is used to assert the form elements and conditions from the Unit test in FormServiceTest & FormTriggerHandler Deep Clone Test
     * @param  cloneForm       form that was cloned 
     * @param  formElementSize the number of form element expected
     * @return                 list of form elements that were retrived in assert is sent back in case further asserts are needed to be done
     */
    public static List<Form_Element__c> formDeepCloneTest_assertFormElements(Form__c cloneForm, Integer formElementSize) {
        Form__c[] f = [SELECT Id, Name FROM Form__c WHERE Id = :cloneForm.Id];
        Assert.areEqual(1, f.size(), 'The form should have been cloned');
        //get form elements
        List<Form_Element__c> elementList = new FormElementSelector().getElementsWithConditionsByFormId(new Set<Id>{cloneForm.Id});
        Assert.areEqual(formElementSize, elementList.size(), 'return all the form elements with conditions for the form');    
        if ( formElementSize > 0 ) {
            String assertMessage = 'Form id must be the same as the one we passed.';
            Assert.areEqual(f[0].Id, elementList[0].Form__c, assertMessage);
            Assert.areEqual(f[0].Id, elementList[1].Form__c, assertMessage);
        }
        return elementList;
    }
}