force-app/force-app/main/default/objects/Form__c/Form__c.object-meta.xml
<CustomObject>
    <description>Create sets of custom questions.</description>
    <label>BT Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BT Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Element__c/Form_Element__c.object-meta.xml
<CustomObject>
    <description>Questions or other types of controls as part of a Form.</description>
    <label>BT Form Element</label>
    <nameField>
        <displayFormat>FE-{000000}</displayFormat>
        <label>Form Element Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT Form Elements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/force-app/main/default/objects/Form_Element__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Form related to this Form Element.</description>
    <inlineHelpText>The Form related to this Form Element.</inlineHelpText>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Form Elements</relationshipLabel>
    <relationshipName>Form_Elements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Element_Condition__c/Form_Element_Condition__c.object-meta.xml
<CustomObject>
    <description>Used for Form Elements with conditional logic.</description>
    <label>BT Form Element Condition</label>
    <nameField>
        <displayFormat>FEC-{000000}</displayFormat>
        <label>Form Element Condition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT Form Element Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Element_Condition__c/fields/Form_Element__c.field-meta.xml
<CustomField>
    <fullName>Form_Element__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The controlling Form Element.</description>
    <inlineHelpText>The controlling Form Element.</inlineHelpText>
    <label>Form Element</label>
    <referenceTo>Form_Element__c</referenceTo>
    <relationshipLabel>Form Element Conditions</relationshipLabel>
    <relationshipName>Form_Element_Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/force-app/main/default/objects/Form_Element_Condition__c/fields/Next_Form_Element__c.field-meta.xml
<CustomField>
    <fullName>Next_Form_Element__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Form Element that will follow if this Element&apos;s conditions are met.</description>
    <inlineHelpText>The Form Element that will follow if this Element&apos;s conditions are met.</inlineHelpText>
    <label>Next Form Element</label>
    <referenceTo>Form_Element__c</referenceTo>
    <relationshipLabel>Form Element Conditions (Next Form Element)</relationshipLabel>
    <relationshipName>Form_Element_Conditions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/force-app/main/default/classes/FormServiceTest.cls
@IsTest
private with sharing class FormServiceTest {
    static Form__c cloneForm;
    private static Map<Id, Id>  getCloneFormData() {
        cloneForm = new Form__c(Name = 'Form Test 2');
        insert cloneForm;

        Map<Id, Id> mapData = new Map<Id, Id>();
        mapData.put(FormTestDataHelper.f1.Id, cloneForm.Id);    
        return mapData;
    }

    @IsTest
    private static void formDeepCloneTest_fullFormClone_expectAllRecordsCreated() {
        FormTestDataHelper.createFormWithElements();
        FormTestDataHelper.setupConditions();
        Map<Id, Id> mapData = getCloneFormData();

        Test.startTest();
        FormService.deepCloneForm(mapData);
        Test.stopTest();

        //get form elements
        List<Form_Element__c> elementList = FormTestDataHelper.formDeepCloneTest_assertFormElements(cloneForm, 2);
        Form_Element__c element0 = elementList[0];
        Form_Element__c element1 = elementList[1];

        //assert conditions
        for (Form_Element__c cond : elementList) {
            Assert.areEqual(
                1,
                cond.Form_Element_Conditions__r.size(),
                'there should be no conditions for the form elements'
            );
            Id nextElementId = cond.Id == element0.Id ? element1.Id : element0.Id;
            Assert.areEqual(
                nextElementId,
                cond.Form_Element_Conditions__r[0].Next_Form_Element__c,
                'This id must match as it child & should be set since we have data'
            );
        }
    }

    @IsTest
    private static void formDeepCloneTest_fullFormClone_expectOnlyFormCreated() {
        FormTestDataHelper.createForm();
        Map<Id, Id> mapData = getCloneFormData();
        Test.startTest();
        FormService.deepCloneForm(mapData);
        Test.stopTest();
        FormTestDataHelper.formDeepCloneTest_assertFormElements(cloneForm, 0);
    }
}