force-app/force-app/main/default/objects/Form__c/Form__c.object-meta.xml
<CustomObject>
    <description>Create sets of custom questions.</description>
    <label>BT Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BT Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Element__c/Form_Element__c.object-meta.xml
<CustomObject>
    <description>Questions or other types of controls as part of a Form.</description>
    <label>BT Form Element</label>
    <nameField>
        <displayFormat>FE-{000000}</displayFormat>
        <label>Form Element Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT Form Elements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/force-app/main/default/objects/Form_Element__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Form related to this Form Element.</description>
    <inlineHelpText>The Form related to this Form Element.</inlineHelpText>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Form Elements</relationshipLabel>
    <relationshipName>Form_Elements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Element_Condition__c/Form_Element_Condition__c.object-meta.xml
<CustomObject>
    <description>Used for Form Elements with conditional logic.</description>
    <label>BT Form Element Condition</label>
    <nameField>
        <displayFormat>FEC-{000000}</displayFormat>
        <label>Form Element Condition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT Form Element Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Element_Condition__c/fields/Form_Element__c.field-meta.xml
<CustomField>
    <fullName>Form_Element__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The controlling Form Element.</description>
    <inlineHelpText>The controlling Form Element.</inlineHelpText>
    <label>Form Element</label>
    <referenceTo>Form_Element__c</referenceTo>
    <relationshipLabel>Form Element Conditions</relationshipLabel>
    <relationshipName>Form_Element_Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/force-app/main/default/classes/FormElementConditionSelectorTest.cls
@IsTest
private class FormElementConditionSelectorTest {
    @IsTest
    private static void testGetSObjectFieldList_expectFieldList() {
        Test.startTest();
        System.assertNotEquals(
            0,
            new FormElementConditionSelector().getSObjectFieldList().size(),
            'Field list is returned from the selector'
        );
        Test.stopTest();
    }

    @IsTest
    private static void testGetSObjectType_expectFormElementObject() {
        Test.startTest();
        Assert.areEqual(
            Form_Element_Condition__c.SObjectType,
            new FormElementConditionSelector().getSObjectType(),
            'It return form elements condition schema type'
        );
        Test.stopTest();
    }
    @IsTest
    private static void getConditionsByFormId_expectRecordReturned() {
        createData();
        Test.startTest();
        List<Form_Element_Condition__c> conditions = new FormElementConditionSelector()
            .getConditionsByFormId(form.Id, 5);
        Test.stopTest();
        Assert.areEqual(2, conditions.size(), 'It returns all conditions for the form');
        Assert.areEqual(fec1.Id, conditions[0].Id, 'It returns the first condition');
        Assert.areEqual(fec2.Id, conditions[1].Id, 'It returns the second condition');
    }

    @IsTest
    private static void getConditionsByFormId_expectNoRecordReturned() {
        createData();
        Test.startTest();
        List<Form_Element_Condition__c> conditions = new FormElementConditionSelector()
            .getConditionsByFormId(Helpers.getFakeId(Form__c.SObjectType), 5);
        Test.stopTest();
        Assert.areEqual(0, conditions.size(), 'It returns no conditions for this form');
    }

    @IsTest
    private static void getConditionsByFormId_expectRecordReturned_limit1() {
        createData();
        Test.startTest();
        List<Form_Element_Condition__c> conditions = new FormElementConditionSelector()
            .getConditionsByFormId(form.Id, 1);
        Assert.areEqual(1, conditions.size(), 'It returns only one condition for the form');
        Assert.areEqual(fec1.Id, conditions[0].Id, 'It returns the first condition');
        Test.stopTest();
    }

    @IsTest
    private static void getConditionsByControlledElement_expectNoRecordReturned() {
        createData();
        Test.startTest();
        List<Form_Element_Condition__c> conditions = new FormElementConditionSelector()
            .getConditionsByControlledElement(new Form_Element__c(), 5);
        Test.stopTest();
        Assert.areEqual(0, conditions.size(), 'It returns no conditions for this form element');
    }

    @IsTest
    private static void getConditionsByControlledElement_expectRecordReturned() {
        createData();
        Test.startTest();
        List<Form_Element_Condition__c> conditions = new FormElementConditionSelector()
            .getConditionsByControlledElement(fe1, 5);

        Test.stopTest();
        Assert.areEqual(1, conditions.size(), 'It returns no conditions for this form element');
        Assert.areEqual(fec2.Id, conditions[0].Id, 'It returns the condition associated with the form element');
    }

    static Form_Element__c fe1, fe2;
    static Form__c form;
    static Form_Element_Condition__c fec1, fec2;
    private static void createData() {
        FormTestDataHelper.createFormWithElements();
        FormTestDataHelper.setupConditions();
        fe1 = FormTestDataHelper.fe1;
        fe2 = FormTestDataHelper.fe2;
        form = FormTestDataHelper.f1;
        fec1 = FormTestDataHelper.fec1;
        fec2 = FormTestDataHelper.fec2;
    }
}