force-app/force-app/main/default/objects/Form__c/Form__c.object-meta.xml
<CustomObject>
    <description>Create sets of custom questions.</description>
    <label>BT Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BT Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/force-app/main/default/objects/Form_Big_List_Group__c/Form_Big_List_Group__c.object-meta.xml
<CustomObject>
    <description>This is used to group Form Big List Option records together to be used in a Form Element (question). This can be used if you have a picklist or type ahead custom question that has more than 1,000 possible options.</description>
    <label>BT Form Big List Group</label>
    <nameField>
        <label>Form Big List Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BT Form Big List Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Element__c/Form_Element__c.object-meta.xml
<CustomObject>
    <description>Questions or other types of controls as part of a Form.</description>
    <label>BT Form Element</label>
    <nameField>
        <displayFormat>FE-{000000}</displayFormat>
        <label>Form Element Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT Form Elements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Element__c/fields/Default_Checkbox_Value__c.field-meta.xml
<CustomField>
    <fullName>Default_Checkbox_Value__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set the default value if the question type is a checkbox.</description>
    <inlineHelpText>Set the default value if the question type is a checkbox.</inlineHelpText>
    <label>Default Checkbox Value</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Form_Element__c/fields/Default_Value__c.field-meta.xml
<CustomField>
    <fullName>Default_Value__c</fullName>
    <description>Set the default value for the Question.</description>
    <inlineHelpText>Set the default value for the Question.</inlineHelpText>
    <label>Default Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/force-app/main/default/objects/Form_Element__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Form related to this Form Element.</description>
    <inlineHelpText>The Form related to this Form Element.</inlineHelpText>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Form Elements</relationshipLabel>
    <relationshipName>Form_Elements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Element__c/fields/Form_Big_List_Group__c.field-meta.xml
<CustomField>
    <fullName>Form_Big_List_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If this Form Element references a Big List Group.</description>
    <inlineHelpText>If this Form Element references a Big List Group.</inlineHelpText>
    <label>Form Big List Group</label>
    <referenceTo>Form_Big_List_Group__c</referenceTo>
    <relationshipLabel>Form Elements</relationshipLabel>
    <relationshipName>Form_Elements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/force-app/main/default/objects/Form_Element__c/fields/Hint__c.field-meta.xml
<CustomField>
    <fullName>Hint__c</fullName>
    <description>A hint for this question (Form Element).</description>
    <inlineHelpText>A hint for this question (Form Element).</inlineHelpText>
    <label>Hint</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Form_Element__c/fields/Maps_To_Field__c.field-meta.xml
<CustomField>
    <fullName>Maps_To_Field__c</fullName>
    <description>This Form Element&apos;s answer should map to this field.</description>
    <inlineHelpText>This Form Element&apos;s answer should map to this field.</inlineHelpText>
    <label>Maps To (Field)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/force-app/main/default/objects/Form_Element__c/fields/Maps_To_Object__c.field-meta.xml
<CustomField>
    <fullName>Maps_To_Object__c</fullName>
    <description>This Form Element&apos;s answer should map to this object.</description>
    <inlineHelpText>This Form Element&apos;s answer should map to this object.</inlineHelpText>
    <label>Maps To (Object)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Element__c/fields/Picklist_Values__c.field-meta.xml
<CustomField>
    <fullName>Picklist_Values__c</fullName>
    <description>The answer values if the question type is a picklist.</description>
    <inlineHelpText>The answer values if the question type is a picklist.</inlineHelpText>
    <label>Picklist Values</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/force-app/main/default/objects/Form_Element__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description>The question of this Form Element.</description>
    <inlineHelpText>The question of this Form Element.</inlineHelpText>
    <label>Question</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/force-app/main/default/objects/Form_Element__c/fields/Question_RT__c.field-meta.xml
<CustomField>
    <fullName>Question_RT__c</fullName>
    <description>Supplemental question information can be used to show terms and conditions or other rich text for a question.</description>
    <inlineHelpText>Supplemental question information can be used to show terms and conditions or other rich text for a question.</inlineHelpText>
    <label>Supplemental Question Information</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Form_Element__c/fields/Required__c.field-meta.xml
<CustomField>
    <fullName>Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If the Form Element is required.</description>
    <inlineHelpText>If the Form Element is required.</inlineHelpText>
    <label>Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/force-app/main/default/objects/Form_Element__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of question or element.</description>
    <inlineHelpText>The type of question or element.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Big List Group</fullName>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Divider</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>File Upload</fullName>
            </value>
            <value>
                <fullName>Hidden</fullName>
            </value>
            <value>
                <fullName>Multi-Select Picklist</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Parameter</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Text (30,000)</fullName>
            </value>
            <value>
                <fullName>URL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_Element_Condition__c/Form_Element_Condition__c.object-meta.xml
<CustomObject>
    <description>Used for Form Elements with conditional logic.</description>
    <label>BT Form Element Condition</label>
    <nameField>
        <displayFormat>FEC-{000000}</displayFormat>
        <label>Form Element Condition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT Form Element Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Element_Condition__c/fields/Form_Element__c.field-meta.xml
<CustomField>
    <fullName>Form_Element__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The controlling Form Element.</description>
    <inlineHelpText>The controlling Form Element.</inlineHelpText>
    <label>Form Element</label>
    <referenceTo>Form_Element__c</referenceTo>
    <relationshipLabel>Form Element Conditions</relationshipLabel>
    <relationshipName>Form_Element_Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/force-app/main/default/objects/Form_Element_Condition__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>Set the order for the questions/Form Elements.</description>
    <inlineHelpText>Set the order for the questions/Form Elements.</inlineHelpText>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/FormElementSelector.cls
public with sharing class FormElementSelector extends fflib_SObjectSelector {

	public static List<Schema.SObjectField> FIELDS_FORM_ELEMENT = new List<Schema.SObjectField> {
		Form_Element__c.Name,
		Form_Element__c.Default_Checkbox_Value__c,
        Form_Element__c.Default_Value__c,
		Form_Element__c.Form__c,
		Form_Element__c.Hint__c,
		Form_Element__c.Maps_To_Field__c,
		Form_Element__c.Maps_To_Object__c,
		Form_Element__c.Picklist_Values__c,
		Form_Element__c.Question__c,
		Form_Element__c.Question_RT__c,
		Form_Element__c.Required__c,
		Form_Element__c.Sort_Order__c,
		Form_Element__c.Type__c,
		Form_Element__c.Form_Big_List_Group__c
	};

	public List<Schema.SObjectField> getSObjectFieldList()
	{
		return FIELDS_FORM_ELEMENT;
	}

    public Schema.SObjectType getSObjectType() {
		return Form_Element__c.SObjectType;
	}

    public List<Form_Element__c> getElementsByFormId(String formId, Integer limitCount) {
        return getElementsByFormId(new Set<Id> {formId}, limitCount);
    }

	public List<Form_Element__c> getElementsByFormId(Set<Id> formId, Integer limitCount) {
        fflib_QueryFactory queryFactory = newQueryFactory();
        queryFactory.setCondition('Form__c = :formId');
        queryFactory.addOrdering('Sort_Order__c', fflib_QueryFactory.SortOrder.DESCENDING);
        queryFactory.addOrdering('CreatedDate', fflib_QueryFactory.SortOrder.ASCENDING);
		if(limitCount != null){
			queryFactory.setLimit(limitCount);
		}
        return (List<Form_Element__c>) Database.query(queryFactory.toSOQL());
    }

	public List<Form_Element__c> getElementsWithConditionsByFormId(Set<Id> formId) {
        fflib_QueryFactory queryFactory = newQueryFactory();
        queryFactory.setCondition('Form__c = :formId');
        queryFactory.addOrdering('Sort_Order__c', fflib_QueryFactory.SortOrder.DESCENDING);
        queryFactory.addOrdering('CreatedDate', fflib_QueryFactory.SortOrder.ASCENDING);
		
		FormElementConditionSelector rs = new FormElementConditionSelector();
        fflib_QueryFactory conditionQueryFactory = rs.newQueryFactory(false);
        rs.addQueryFactorySubselect(queryFactory, Helpers.getFieldObjectNS()+'Form_Element_Conditions__r'); 
        return (List<Form_Element__c>) Database.query(queryFactory.toSOQL());
    }

    public Form_Element__c selectById(Id recordId){
        Set<Id> recordIds = new Set<Id>{recordId};
        List<Form_Element__c> elements = selectSObjectsById(recordIds);
        return elements.isEmpty() ? null : elements.get(0);
    }
}