force-app/force-app/main/default/objects/Form__c/Form__c.object-meta.xml
<CustomObject>
    <description>Create sets of custom questions.</description>
    <label>BT Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BT Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/force-app/main/default/objects/Form_Big_List_Group__c/Form_Big_List_Group__c.object-meta.xml
<CustomObject>
    <description>This is used to group Form Big List Option records together to be used in a Form Element (question). This can be used if you have a picklist or type ahead custom question that has more than 1,000 possible options.</description>
    <label>BT Form Big List Group</label>
    <nameField>
        <label>Form Big List Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BT Form Big List Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Element__c/Form_Element__c.object-meta.xml
<CustomObject>
    <description>Questions or other types of controls as part of a Form.</description>
    <label>BT Form Element</label>
    <nameField>
        <displayFormat>FE-{000000}</displayFormat>
        <label>Form Element Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT Form Elements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/force-app/main/default/objects/Form_Element__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Form related to this Form Element.</description>
    <inlineHelpText>The Form related to this Form Element.</inlineHelpText>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Form Elements</relationshipLabel>
    <relationshipName>Form_Elements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Element__c/fields/Form_Big_List_Group__c.field-meta.xml
<CustomField>
    <fullName>Form_Big_List_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If this Form Element references a Big List Group.</description>
    <inlineHelpText>If this Form Element references a Big List Group.</inlineHelpText>
    <label>Form Big List Group</label>
    <referenceTo>Form_Big_List_Group__c</referenceTo>
    <relationshipLabel>Form Elements</relationshipLabel>
    <relationshipName>Form_Elements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Element__c/fields/Maps_To_Field__c.field-meta.xml
<CustomField>
    <fullName>Maps_To_Field__c</fullName>
    <description>This Form Element&apos;s answer should map to this field.</description>
    <inlineHelpText>This Form Element&apos;s answer should map to this field.</inlineHelpText>
    <label>Maps To (Field)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/force-app/main/default/objects/Form_Element__c/fields/Maps_To_Object__c.field-meta.xml
<CustomField>
    <fullName>Maps_To_Object__c</fullName>
    <description>This Form Element&apos;s answer should map to this object.</description>
    <inlineHelpText>This Form Element&apos;s answer should map to this object.</inlineHelpText>
    <label>Maps To (Object)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/force-app/main/default/objects/Form_Element__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description>The question of this Form Element.</description>
    <inlineHelpText>The question of this Form Element.</inlineHelpText>
    <label>Question</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/force-app/main/default/objects/Form_Element__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of question or element.</description>
    <inlineHelpText>The type of question or element.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Big List Group</fullName>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Divider</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>File Upload</fullName>
            </value>
            <value>
                <fullName>Hidden</fullName>
            </value>
            <value>
                <fullName>Multi-Select Picklist</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Parameter</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Text (30,000)</fullName>
            </value>
            <value>
                <fullName>URL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_Element_Condition__c/Form_Element_Condition__c.object-meta.xml
<CustomObject>
    <description>Used for Form Elements with conditional logic.</description>
    <label>BT Form Element Condition</label>
    <nameField>
        <displayFormat>FEC-{000000}</displayFormat>
        <label>Form Element Condition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT Form Element Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Element_Condition__c/fields/Condition_Operator__c.field-meta.xml
<CustomField>
    <fullName>Condition_Operator__c</fullName>
    <description>The operator by which this condition is evaluated.</description>
    <inlineHelpText>The operator by which this condition is evaluated.</inlineHelpText>
    <label>Condition Operator</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contains</fullName>
            </value>
            <value>
                <fullName>Equals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/force-app/main/default/objects/Form_Element_Condition__c/fields/Condition_Value__c.field-meta.xml
<CustomField>
    <fullName>Condition_Value__c</fullName>
    <description>The value used to evaluate this condition.</description>
    <inlineHelpText>The value used to evaluate this condition.</inlineHelpText>
    <label>Condition Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Element_Condition__c/fields/Form_Element__c.field-meta.xml
<CustomField>
    <fullName>Form_Element__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The controlling Form Element.</description>
    <inlineHelpText>The controlling Form Element.</inlineHelpText>
    <label>Form Element</label>
    <referenceTo>Form_Element__c</referenceTo>
    <relationshipLabel>Form Element Conditions</relationshipLabel>
    <relationshipName>Form_Element_Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/force-app/main/default/objects/Form_Element_Condition__c/fields/Next_Form_Element__c.field-meta.xml
<CustomField>
    <fullName>Next_Form_Element__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Form Element that will follow if this Element&apos;s conditions are met.</description>
    <inlineHelpText>The Form Element that will follow if this Element&apos;s conditions are met.</inlineHelpText>
    <label>Next Form Element</label>
    <referenceTo>Form_Element__c</referenceTo>
    <relationshipLabel>Form Element Conditions (Next Form Element)</relationshipLabel>
    <relationshipName>Form_Element_Conditions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/force-app/main/default/classes/FormControllerTest.cls
@IsTest
private with sharing class FormControllerTest {
    static Form_Element__c fe1, fe2;
    static Form__c form;
    static Form_Element_Condition__c fec1, fec2;

    private static void createForm() {
        form = new Form__c(Name = 'Contact');
        insert new List<Form__c>{ form };
    }

    private static void createData() {
        createForm();
        fe1 = buildFormElement();
        fe2 = buildFormElement();
        insert new List<Form_Element__c>{ fe1, fe2 };

        fec1 = buildFormElementCondition(fe1.Id, fe2.Id);
        fec2 = buildFormElementCondition(fe2.Id, fe1.Id);
        insert new List<Form_Element_Condition__c>{ fec1, fec2 };
    }

    private static Form_Element__c buildFormElement() {
        Form_Element__c fe = new Form_Element__c(
            Question__c = 'Where is Spiderman?',
            Type__c = 'Text',
            Maps_To_Object__c = 'Contact',
            Maps_To_Field__c = 'FirstName',
            Form__c = form.Id
        );
        return fe;
    }

    private static Form_Element_Condition__c buildFormElementCondition(Id feId1, Id feId2) {
        Form_Element_Condition__c fec = new Form_Element_Condition__c(
            Form_Element__c = feId1,
            Condition_Operator__c = 'Equals',
            Condition_Value__c = 'Peter Parker',
            Next_Form_Element__c = feId2
        );
        return fec;
    }

    @IsTest
    private static void listMapToObjects_expectRecordsReturned() {
        createData();
        Test.startTest();
        List<FormController.MapToList> listOfObjects = FormController.listMapToObjects();
        Test.stopTest();
        Assert.isTrue(listOfObjects.size() == 3, 'There are 3 configured records');
    }

    @IsTest
    private static void loadFormElements_expectRecordsReturned() {
        createData();
        Test.startTest();
        List<Form_Element__c> formElements = FormController.loadFormElements(form.Id);
        Test.stopTest();
        Assert.areEqual(2, formElements.size(), 'Expected 2 form elements');
    }

    @IsTest
    private static void loadFormElements_expectNoRecordsReturned() {
        createData();
        Test.startTest();
        List<Form_Element__c> formElements = FormController.loadFormElements(Helpers.getFakeId(Form__c.SobjectType));
        Test.stopTest();
        Assert.areEqual(0, formElements.size(), 'There are no form elements for this form');
    }

    @IsTest
    private static void loadFormElementConditions_expectNoRecordsReturned() {
        createData();
        Test.startTest();
        List<Form_Element_Condition__c> formElements = FormController.loadFormElementConditions(
            Helpers.getFakeId(Form__c.SobjectType)
        );
        Test.stopTest();
        Assert.areEqual(0, formElements.size(), 'There are no form elements conditions for this form');
    }

    @IsTest
    private static void loadFormElementConditions_expectRecordsReturned() {
        createData();
        Test.startTest();
        List<Form_Element_Condition__c> formElements = FormController.loadFormElementConditions(form.Id);
        Test.stopTest();
        Assert.areEqual(2, formElements.size(), 'It should return 2 form elements conditions');
    }

    @IsTest
    private static void loadBigListGroups_expectRecordsReturned() {
        Form_Big_List_Group__c group1 = new Form_Big_List_Group__c(Name = 'Group 1');
        Form_Big_List_Group__c group2 = new Form_Big_List_Group__c(Name = 'Group 2');

        insert new List<Form_Big_List_Group__c>{ group1, group2 };
        Test.startTest();
        List<Form_Big_List_Group__c> groups = FormController.loadBigListGroups();
        Test.stopTest();
        Assert.areEqual(2, groups.size(), 'It should return all groups');
    }

    @IsTest
    private static void saveElementAndConditions_expectRecordsSaved() {
        createForm();
        fe1 = buildFormElement();
        fec1 = buildFormElementCondition(null, null);
        insert fec1;
        Test.startTest();
        FormController.FormElementAndConditions response = FormController.saveElementAndConditions(
            fe1,
            new List<Form_Element_Condition__c>{ buildFormElementCondition(null, null) },
            new List<Form_Element_Condition__c>{ fec1 }
        );
        Test.stopTest();

        Assert.areEqual(fe1.Id, response.element.Id, 'The save element should be returned');

        List<Form_Element__c> formElements = [SELECT Id FROM Form_Element__c];
        List<Form_Element_Condition__c> formElementConditions = [SELECT Id FROM Form_Element_Condition__c];
        Assert.areEqual(1, formElements.size(), 'It should save 1 form element');
        Assert.areEqual(1, formElementConditions.size(), 'It should save 1 form element condition');

        formElementConditions = [SELECT Id, Form_Element__c FROM Form_Element_Condition__c WHERE Id = :fec1.Id];
        Assert.areEqual(0, formElementConditions.size(), 'This condition should be deleted');
    }

    @IsTest
    private static void saveElementAndConditions_expectError() {
        createForm();
        fe1 = buildFormElement();
        fec1 = buildFormElementCondition(null, null);
        insert fec1;
        Boolean hasError = false;
        FormController.MAX_LIMIT = 1;
        Test.startTest();
        try {
            FormController.FormElementAndConditions response = FormController.saveElementAndConditions(
                fe1,
                new List<Form_Element_Condition__c>{ buildFormElementCondition(null, null) },
                new List<Form_Element_Condition__c>{ fec1 }
            );
        } catch (AuraHandledException e) {
            hasError = true;
            Assert.isTrue(e.getMessage().contains(Label.Form_Builder_Max_Limit), 'It should throw an error');
        }
        Test.stopTest();
        Assert.isTrue(hasError, 'There should be an error thrown for max limit');
    }

    @IsTest
    private static void saveFormElements_expectRecordsSaved() {
        createForm();
        fe1 = buildFormElement();
        fe2 = buildFormElement();
        fe2.Question__c = 'Where is Batman?';
        Test.startTest();
        FormController.saveFormElements(new List<Form_Element__c>{ fe1, fe2 });
        Test.stopTest();

        List<Form_Element__c> formElements = [SELECT Id FROM Form_Element__c];
        Assert.areEqual(2, formElements.size(), 'It should save 2 form element');
    }

    @IsTest
    private static void saveFormElements_expectError() {
        createForm();
        fe1 = buildFormElement();
        fe2 = buildFormElement();
        fe2.Question__c = 'Where is Batman?';
        FormController.MAX_LIMIT = 1;
        Boolean hasError = false;
        Test.startTest();
        try {
            FormController.saveFormElements(new List<Form_Element__c>{ fe1, fe2 });
        } catch (AuraHandledException e) {
            hasError = true;
            Assert.isTrue(e.getMessage().contains(Label.Form_Builder_Max_Limit), 'It should throw an error');
        }
        Test.stopTest();
        Assert.isTrue(hasError, 'There should be an error thrown for max limit');
    }

    @IsTest
    private static void deleteFormElements_expectRecordsSaved() {
        createData();
        Test.startTest();
        FormController.deleteFormElements(new List<Form_Element__c>{ fe1, fe2 });
        Test.stopTest();

        List<Form_Element__c> formElements = [SELECT Id FROM Form_Element__c];
        Assert.areEqual(0, formElements.size(), 'Both of the form elements should be deleted');
    }

    @IsTest
    private static void deleteFormElements_expectError() {
        createData();

        FormController.MAX_LIMIT = 1;
        Boolean hasError = false;
        Test.startTest();
        try {
            FormController.deleteFormElements(new List<Form_Element__c>{ fe1, fe2 });
        } catch (Exception e) {
            hasError = true;
            Assert.isTrue(e.getMessage().contains(Label.Form_Builder_Max_Limit), 'It should throw an error');
        }
        Test.stopTest();
        Assert.isTrue(hasError, 'There should be an error thrown for max limit');
    }
}