force-app/force-app/main/default/objects/Form__c/Form__c.object-meta.xml
<CustomObject>
    <description>Create sets of custom questions.</description>
    <label>BT Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BT Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Element__c/Form_Element__c.object-meta.xml
<CustomObject>
    <description>Questions or other types of controls as part of a Form.</description>
    <label>BT Form Element</label>
    <nameField>
        <displayFormat>FE-{000000}</displayFormat>
        <label>Form Element Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT Form Elements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/force-app/main/default/objects/Form_Element__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Form related to this Form Element.</description>
    <inlineHelpText>The Form related to this Form Element.</inlineHelpText>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Form Elements</relationshipLabel>
    <relationshipName>Form_Elements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Element_Condition__c/Form_Element_Condition__c.object-meta.xml
<CustomObject>
    <description>Used for Form Elements with conditional logic.</description>
    <label>BT Form Element Condition</label>
    <nameField>
        <displayFormat>FEC-{000000}</displayFormat>
        <label>Form Element Condition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT Form Element Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Element_Condition__c/fields/Condition_Operator__c.field-meta.xml
<CustomField>
    <fullName>Condition_Operator__c</fullName>
    <description>The operator by which this condition is evaluated.</description>
    <inlineHelpText>The operator by which this condition is evaluated.</inlineHelpText>
    <label>Condition Operator</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contains</fullName>
            </value>
            <value>
                <fullName>Equals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/force-app/main/default/objects/Form_Element_Condition__c/fields/Condition_Value__c.field-meta.xml
<CustomField>
    <fullName>Condition_Value__c</fullName>
    <description>The value used to evaluate this condition.</description>
    <inlineHelpText>The value used to evaluate this condition.</inlineHelpText>
    <label>Condition Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Element_Condition__c/fields/Form_Element__c.field-meta.xml
<CustomField>
    <fullName>Form_Element__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The controlling Form Element.</description>
    <inlineHelpText>The controlling Form Element.</inlineHelpText>
    <label>Form Element</label>
    <referenceTo>Form_Element__c</referenceTo>
    <relationshipLabel>Form Element Conditions</relationshipLabel>
    <relationshipName>Form_Element_Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/force-app/main/default/objects/Form_Element_Condition__c/fields/Next_Form_Element__c.field-meta.xml
<CustomField>
    <fullName>Next_Form_Element__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Form Element that will follow if this Element&apos;s conditions are met.</description>
    <inlineHelpText>The Form Element that will follow if this Element&apos;s conditions are met.</inlineHelpText>
    <label>Next Form Element</label>
    <referenceTo>Form_Element__c</referenceTo>
    <relationshipLabel>Form Element Conditions (Next Form Element)</relationshipLabel>
    <relationshipName>Form_Element_Conditions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/force-app/main/default/classes/FormElementConditionSelector.cls
public with sharing class FormElementConditionSelector extends fflib_SObjectSelector {
    public static List<Schema.SObjectField> FIELDS_FORM_ELEMENT_CONDITION = new List<Schema.SObjectField>{
        Form_Element_Condition__c.Name,
        Form_Element_Condition__c.Condition_Operator__c,
        Form_Element_Condition__c.Condition_Value__c,
        Form_Element_Condition__c.Form_Element__c,
        Form_Element_Condition__c.Next_Form_Element__c
    };

    public List<Schema.SObjectField> getSObjectFieldList() {
        return FIELDS_FORM_ELEMENT_CONDITION;
    }

    public Schema.SObjectType getSObjectType() {
        return Form_Element_Condition__c.SObjectType;
    }

    public List<Form_Element_Condition__c> getConditionsByFormId(Id formId, Integer limitCount) {
        fflib_QueryFactory queryFactory = newQueryFactory();
        queryFactory.setCondition('Form_Element__r.Form__c = :formId AND Next_Form_Element__r.Form__c = :formId');
        queryFactory.addOrdering('CreatedDate', fflib_QueryFactory.SortOrder.ASCENDING);
        queryFactory.setLimit(limitCount);
        return (List<Form_Element_Condition__c>) Database.query(queryFactory.toSOQL());
    }

    public List<Form_Element_Condition__c> getConditionsByControlledElement(
        Form_Element__c element,
        Integer limitCount
    ) {
        fflib_QueryFactory queryFactory = newQueryFactory();
        Id formId = element.Form__c;
        Id elementId = element.Id;
        queryFactory.setCondition(
            'Form_Element__r.Form__c = :formId AND Next_Form_Element__r.Form__c = :formId and Next_Form_Element__c = :elementId'
        );
        queryFactory.addOrdering('CreatedDate', fflib_QueryFactory.SortOrder.ASCENDING);
        queryFactory.setLimit(limitCount);
        return (List<Form_Element_Condition__c>) Database.query(queryFactory.toSOQL());
    }
}