force-app/force-app/main/default/objects/Form__c/Form__c.object-meta.xml
<CustomObject>
    <description>Create sets of custom questions.</description>
    <label>BT Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BT Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/force-app/main/default/objects/Form__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Indexed key field that is used by Blackthorn APIs and URLs.</description>
    <externalId>true</externalId>
    <inlineHelpText>Indexed key field that is used by Blackthorn APIs and URLs.</inlineHelpText>
    <label>Key</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Form_Big_List_Option__c/Form_Big_List_Option__c.object-meta.xml
<CustomObject>
    <description>Possible selections for your Big List.</description>
    <label>BT Form Big List Option</label>
    <nameField>
        <displayFormat>FBLO-{000000}</displayFormat>
        <label>Form Big List Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT Form Big List Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Element__c/Form_Element__c.object-meta.xml
<CustomObject>
    <description>Questions or other types of controls as part of a Form.</description>
    <label>BT Form Element</label>
    <nameField>
        <displayFormat>FE-{000000}</displayFormat>
        <label>Form Element Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT Form Elements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/force-app/main/default/objects/Form_Element__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Form related to this Form Element.</description>
    <inlineHelpText>The Form related to this Form Element.</inlineHelpText>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Form Elements</relationshipLabel>
    <relationshipName>Form_Elements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/force-app/main/default/objects/Form_Element__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Indexed key field that is used by Blackthorn APIs and URLs. Generated with before insert and update triggers if is ever blank.</description>
    <externalId>true</externalId>
    <inlineHelpText>Indexed key field that is used by Blackthorn APIs and URLs. Generated with before insert and update triggers if is ever blank.</inlineHelpText>
    <label>Key</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/force-app/main/default/objects/Form_Element__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description>The question of this Form Element.</description>
    <inlineHelpText>The question of this Form Element.</inlineHelpText>
    <label>Question</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/force-app/main/default/objects/Form_Submission__c/Form_Submission__c.object-meta.xml
<CustomObject>
    <description>Submissions from forms or custom questions related to Blackthorn apps.</description>
    <label>BT Form Submission</label>
    <nameField>
        <displayFormat>FS-{000000}</displayFormat>
        <label>Form Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT Form Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Submission__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Form that originated this Form Submission.</description>
    <inlineHelpText>The Form that originated this Form Submission.</inlineHelpText>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Form Submissions</relationshipLabel>
    <relationshipName>Form_Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Submission_Answer__c/Form_Submission_Answer__c.object-meta.xml
<CustomObject>
    <description>Each submitted form answer is saved here.</description>
    <label>BT Form Submission Answer</label>
    <nameField>
        <displayFormat>FSA-{000000}</displayFormat>
        <label>Form Submission Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT Form Submission Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Submission_Answer__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <description>The submitted answer for this record.</description>
    <inlineHelpText>The submitted answer for this record.</inlineHelpText>
    <label>Answer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/force-app/main/default/objects/Form_Submission_Answer__c/fields/Answer_Date__c.field-meta.xml
<CustomField>
    <fullName>Answer_Date__c</fullName>
    <description>If the answer was in the form of a date.</description>
    <inlineHelpText>If the answer was in the form of a date.</inlineHelpText>
    <label>Answer Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Form_Submission_Answer__c/fields/Answer_Mapped__c.field-meta.xml
<CustomField>
    <fullName>Answer_Mapped__c</fullName>
    <description>The date/time that the answer was mapped.</description>
    <inlineHelpText>The date/time that the answer was mapped.</inlineHelpText>
    <label>Answer Mapped</label>
    <type>DateTime</type>
</CustomField>

force-app/force-app/main/default/objects/Form_Submission_Answer__c/fields/Answer_Number__c.field-meta.xml
<CustomField>
    <fullName>Answer_Number__c</fullName>
    <description>If the answer was in the form of a number.</description>
    <inlineHelpText>If the answer was in the form of a number.</inlineHelpText>
    <label>Answer Number</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/force-app/main/default/objects/Form_Submission_Answer__c/fields/Answer_Text_Long__c.field-meta.xml
<CustomField>
    <fullName>Answer_Text_Long__c</fullName>
    <description>If the answer was in the form of long text.</description>
    <inlineHelpText>If the answer was in the form of long text.</inlineHelpText>
    <label>Answer Text Long</label>
    <length>30000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/force-app/main/default/objects/Form_Submission_Answer__c/fields/File_Upload_Key__c.field-meta.xml
<CustomField>
    <fullName>File_Upload_Key__c</fullName>
    <description>A unique key that references the uploaded file to this record.</description>
    <inlineHelpText>A unique key that references the uploaded file to this record.</inlineHelpText>
    <label>File Upload Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/force-app/main/default/objects/Form_Submission_Answer__c/fields/Form_Big_List_Option__c.field-meta.xml
<CustomField>
    <fullName>Form_Big_List_Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The related big list option if this record was from a big list submission.</description>
    <inlineHelpText>The related big list option if this record was from a big list submission.</inlineHelpText>
    <label>Form Big List Option</label>
    <referenceTo>Form_Big_List_Option__c</referenceTo>
    <relationshipLabel>Form Submission Answers</relationshipLabel>
    <relationshipName>Form_Submission_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Submission_Answer__c/fields/Form_Element__c.field-meta.xml
<CustomField>
    <fullName>Form_Element__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Form Element related to this record.</description>
    <inlineHelpText>The Form Element related to this record.</inlineHelpText>
    <label>Form Element</label>
    <referenceTo>Form_Element__c</referenceTo>
    <relationshipLabel>Form Submission Answers</relationshipLabel>
    <relationshipName>Form_Submission_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/force-app/main/default/objects/Form_Submission_Answer__c/fields/Form_Submission__c.field-meta.xml
<CustomField>
    <fullName>Form_Submission__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The originating Form Submission.</description>
    <inlineHelpText>The originating Form Submission.</inlineHelpText>
    <label>Form Submission</label>
    <referenceTo>Form_Submission__c</referenceTo>
    <relationshipLabel>Form Submission Answers</relationshipLabel>
    <relationshipName>Form_Submission_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/force-app/main/default/objects/Form_Submission_Answer__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description>The question of the related Form Element.</description>
    <inlineHelpText>The question of the related Form Element.</inlineHelpText>
    <label>Question</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/force-app/main/default/classes/FormSubmissionAnswerSelector.cls
public with sharing class FormSubmissionAnswerSelector extends fflib_SObjectSelector {
    public static List<Schema.SObjectField> FIELDS_FORM_ANSWER = new List<Schema.SObjectField>{
        Form_Submission_Answer__c.Name,
        Form_Submission_Answer__c.Answer__c,
        Form_Submission_Answer__c.Answer_Text_Long__c,
        Form_Submission_Answer__c.Answer_Date__c,
        Form_Submission_Answer__c.Answer_Number__c,
        Form_Submission_Answer__c.File_Upload_Key__c,
        Form_Submission_Answer__c.Form_Big_List_Option__c,
        Form_Submission_Answer__c.Form_Element__c,
        Form_Submission_Answer__c.Answer_Mapped__c,
        Form_Submission_Answer__c.Form_Submission__c,
        Form_Submission_Answer__c.Question__c
    };

    public List<Schema.SObjectField> getSObjectFieldList() {
        return FIELDS_FORM_ANSWER;
    }

    public Schema.SObjectType getSObjectType() {
        return Form_Submission_Answer__c.SObjectType;
    }

    public List<Form_Submission_Answer__c> getAnswerByFormSubmissionId(Set<Id> formSubmissionIds) {
        return [
            SELECT
                Name,
                Answer__c,
                Answer_Text_Long__c,
                Answer_Date__c,
                Answer_Number__c,
                File_Upload_Key__c,
                Form_Big_List_Option__c,
                Form_Element__c,
                Answer_Mapped__c,
                Form_Submission__c,
                Question__c,
                Form_Submission__r.Form__c,
                Form_Submission__r.Key__c
            FROM Form_Submission_Answer__c
            WHERE Form_Submission__c IN :formSubmissionIds
            WITH SECURITY_ENFORCED
        ];
    }
}