force-app/force-app/main/default/objects/Form__c/Form__c.object-meta.xml
<CustomObject>
    <description>Create sets of custom questions.</description>
    <label>BT Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BT Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Element__c/Form_Element__c.object-meta.xml
<CustomObject>
    <description>Questions or other types of controls as part of a Form.</description>
    <label>BT Form Element</label>
    <nameField>
        <displayFormat>FE-{000000}</displayFormat>
        <label>Form Element Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT Form Elements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/force-app/main/default/objects/Form_Element__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Form related to this Form Element.</description>
    <inlineHelpText>The Form related to this Form Element.</inlineHelpText>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Form Elements</relationshipLabel>
    <relationshipName>Form_Elements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Element_Condition__c/Form_Element_Condition__c.object-meta.xml
<CustomObject>
    <description>Used for Form Elements with conditional logic.</description>
    <label>BT Form Element Condition</label>
    <nameField>
        <displayFormat>FEC-{000000}</displayFormat>
        <label>Form Element Condition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT Form Element Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Element_Condition__c/fields/Form_Element__c.field-meta.xml
<CustomField>
    <fullName>Form_Element__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The controlling Form Element.</description>
    <inlineHelpText>The controlling Form Element.</inlineHelpText>
    <label>Form Element</label>
    <referenceTo>Form_Element__c</referenceTo>
    <relationshipLabel>Form Element Conditions</relationshipLabel>
    <relationshipName>Form_Element_Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/force-app/main/default/objects/Form_Element_Condition__c/fields/Next_Form_Element__c.field-meta.xml
<CustomField>
    <fullName>Next_Form_Element__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Form Element that will follow if this Element&apos;s conditions are met.</description>
    <inlineHelpText>The Form Element that will follow if this Element&apos;s conditions are met.</inlineHelpText>
    <label>Next Form Element</label>
    <referenceTo>Form_Element__c</referenceTo>
    <relationshipLabel>Form Element Conditions (Next Form Element)</relationshipLabel>
    <relationshipName>Form_Element_Conditions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FormService.cls
/**
 *  This is your main service class. It is used to handle all the logic of your form related tasks.
 */
public with sharing class FormService {
    /**
     * This method is used to clone a form and all its elements and conditions.
     * @param formIdWithSource - a map of parent form Id along with clone version of the form Id
     */
    public static void deepCloneForm(Map<Id, Id> formIdWithSource) {
        fflib_SObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(
            new List<Schema.SObjectType>{ Form_Element__c.SObjectType, Form_Element_Condition__c.SObjectType }
        );

        List<Form_Element__c> formElements = new FormElementSelector()
            .getElementsWithConditionsByFormId(formIdWithSource.keySet());
        Map<Id, Form_Element__c> elementIdToCloneMap = new Map<Id, Form_Element__c>();
        for (Form_Element__c element : formElements) {
            Form_Element__c clone = element.clone(false, true);
            clone.Form__c = formIdWithSource.get(element.Form__c);
            uow.registerNew(clone);
            elementIdToCloneMap.put(element.Id, clone);
        }

        //next clone all the conditions
        for (Form_Element__c element : formElements) {
            if (element.Form_Element_Conditions__r != null && !element.Form_Element_Conditions__r.isEmpty()) {
                for (Form_Element_Condition__c condition : element.Form_Element_Conditions__r) {
                    Form_Element_Condition__c clone = condition.clone(false, true);
                    uow.registerRelationship(
                        clone,
                        Form_Element_Condition__c.Form_Element__c,
                        elementIdToCloneMap.get(condition.Form_Element__c)
                    );
                    uow.registerRelationship(
                        clone,
                        Form_Element_Condition__c.Next_Form_Element__c,
                        elementIdToCloneMap.get(condition.Next_Form_Element__c)
                    );
                    uow.registerNew(clone);
                }
            }
        }
        //finally commit the work
        uow.commitWork();
    }
}