force-app/force-app/main/default/objects/Form__c/Form__c.object-meta.xml
<CustomObject>
    <description>Create sets of custom questions.</description>
    <label>BT Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BT Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/force-app/main/default/objects/Form__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Indexed key field that is used by Blackthorn APIs and URLs.</description>
    <externalId>true</externalId>
    <inlineHelpText>Indexed key field that is used by Blackthorn APIs and URLs.</inlineHelpText>
    <label>Key</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/force-app/main/default/objects/Form_Submission__c/Form_Submission__c.object-meta.xml
<CustomObject>
    <description>Submissions from forms or custom questions related to Blackthorn apps.</description>
    <label>BT Form Submission</label>
    <nameField>
        <displayFormat>FS-{000000}</displayFormat>
        <label>Form Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BT Form Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Submission__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If this Form Submission was submitted by a matching Account.</description>
    <inlineHelpText>If this Form Submission was submitted by a matching Account.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Form Submissions</relationshipLabel>
    <relationshipName>Form_Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/force-app/main/default/objects/Form_Submission__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If this Form Submission was submitted by a matching Contact.</description>
    <inlineHelpText>If this Form Submission was submitted by a matching Contact.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Form Submissions</relationshipLabel>
    <relationshipName>Form_Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Submission__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Form that originated this Form Submission.</description>
    <inlineHelpText>The Form that originated this Form Submission.</inlineHelpText>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Form Submissions</relationshipLabel>
    <relationshipName>Form_Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/force-app/main/default/objects/Form_Submission__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If the Form Submission was submitted by a matching Lead.</description>
    <inlineHelpText>If the Form Submission was submitted by a matching Lead.</inlineHelpText>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Form Submissions</relationshipLabel>
    <relationshipName>Form_Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Submission__c/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <description>The JSON code containing the full form submission contents.</description>
    <inlineHelpText>The JSON code containing the full form submission contents.</inlineHelpText>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Form_Submission__c/fields/Processed__c.field-meta.xml
<CustomField>
    <fullName>Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This submission was processed successfully.</description>
    <inlineHelpText>This submission was processed successfully.</inlineHelpText>
    <label>Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Form_Submission__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The processing status for this form submission.</description>
    <inlineHelpText>The processing status for this form submission.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>To Process</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_Submission__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If this form was submitted by a User it&apos;s stored here.</description>
    <inlineHelpText>If this form was submitted by a User it&apos;s stored here.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Form Submissions</relationshipLabel>
    <relationshipName>Form_Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/force-app/main/default/classes/FormSubmissionSelector.cls
public with sharing class FormSubmissionSelector extends fflib_SObjectSelector {

	public static List<Schema.SObjectField> FIELDS_FORMSUBMISSION = new List<Schema.SObjectField> {
		Form_Submission__c.Name,
		Form_Submission__c.Form__c,
		Form_Submission__c.Key__c,
		Form_Submission__c.Contact__c,
		Form_Submission__c.Lead__c,
		Form_Submission__c.Account__c,
		Form_Submission__c.User__c,
		Form_Submission__c.Payload__c,
		Form_Submission__c.Status__c
	};

	public List<Schema.SObjectField> getSObjectFieldList()
	{
		return FIELDS_FORMSUBMISSION;
	}

	public String getFormProcessingBatchQuery(){

		FIELDS_FORMSUBMISSION = Form_Submission__c.SObjectType.getDescribe().fields.getMap().values();

		fflib_QueryFactory formQueryFactory = newQueryFactory();
		formQueryFactory.setCondition('Status__c = \''+FormSubmissionAPIService.STATUS_TOPROCESS+'\' AND Processed__c = false');

		fflib_QueryFactory formAnswersSubSelectQuery = new 
		FormSubmissionAnswerSelector().addQueryFactorySubselect(formQueryFactory).setCondition('Form_Submission__c != null AND Form_Element__r.Maps_To_Object__c != null');
		formAnswersSubSelectQuery.selectField('Form_Element__r.Type__c');
		formAnswersSubSelectQuery.selectField('Form_Element__r.Maps_To_Field__c');
		formAnswersSubSelectQuery.selectField('Form_Element__r.Maps_To_Object__c');
		formAnswersSubSelectQuery.selectField('Form_Element__r.Form__c');
		return formQueryFactory.toSOQL();
	}

	public List<Form_Submission__c> getSubmissionByKey(Set<String> keys){
		keys.remove(null);
		fflib_QueryFactory formQueryFactory = newQueryFactory();
		formQueryFactory.setCondition('Key__c in :keys');
		fflib_QueryFactory formAnswersSubSelectQuery = new FormSubmissionAnswerSelector().addQueryFactorySubselect(formQueryFactory);
		return (List<Form_Submission__c>) Database.query(formQueryFactory.toSOQL());
	}

	public Schema.SObjectType getSObjectType() {
		return Form_Submission__c.SObjectType;
	}
}