force-app/main/default/objects/SCH_Schedule__c/SCH_Schedule__c.object-meta.xml
<CustomObject>
    <label>Schedule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/force-app/main/default/objects/SCH_Schedule__c/fields/Base_Object__c.field-meta.xml
<CustomField>
    <fullName>Base_Object__c</fullName>
    <label>Base Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/force-app/main/default/objects/SCH_Schedule__c/fields/Base_Object_Evaluate_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Base_Object_Evaluate_Criteria__c</fullName>
    <label>Base Object Evaluate Criteria</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/force-app/main/default/objects/SCH_Schedule__c/fields/Base_Object_Evaluate_Criteria_JSON__c.field-meta.xml
<CustomField>
    <fullName>Base_Object_Evaluate_Criteria_JSON__c</fullName>
    <label>Base Object Evaluate Criteria JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SCH_Schedule__c/fields/Offset__c.field-meta.xml
<CustomField>
    <fullName>Offset__c</fullName>
    <label>Offset</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>before</fullName>
                <label>Before</label>
            </value>
            <value>
                <fullName>after</fullName>
                <label>After</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SCH_Schedule__c/fields/Offset_Type__c.field-meta.xml
<CustomField>
    <fullName>Offset_Type__c</fullName>
    <label>Offset Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>days</fullName>
                <label>Days</label>
            </value>
            <value>
                <fullName>hours</fullName>
                <label>Hours</label>
            </value>
            <value>
                <fullName>minutes</fullName>
                <label>Minutes</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SCH_Schedule__c/fields/Offset_Value__c.field-meta.xml
<CustomField>
    <fullName>Offset_Value__c</fullName>
    <label>Offset Value</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/force-app/main/default/objects/SCH_Schedule__c/fields/Related_Object_Evaluate_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Related_Object_Evaluate_Criteria__c</fullName>
    <label>Related Object Evaluate Criteria</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SCH_Schedule__c/fields/Related_Object_Evaluate_Criteria_JSON__c.field-meta.xml
<CustomField>
    <fullName>Related_Object_Evaluate_Criteria_JSON__c</fullName>
    <label>Related Object Evaluate Criteria JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/force-app/main/default/objects/SCH_Schedule__c/fields/Schedule_Date_Time_Field__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Date_Time_Field__c</fullName>
    <label>Schedule Date/Time Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/force-app/main/default/objects/SCH_Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>draft</fullName>
                <label>Draft</label>
            </value>
            <value>
                <fullName>processing</fullName>
                <label>Processing</label>
            </value>
            <value>
                <fullName>scheduled</fullName>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>completed</fullName>
                <label>Completed</label>
            </value>
            <value>
                <fullName>canceled</fullName>
                <label>Canceled</label>
            </value>
            <value>
                <fullName>failed</fullName>
                <label>Failed</label>
            </value>
            <value>
                <fullName>inactive</fullName>
                <label>Unschedule</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SCH_Schedule__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>record</fullName>
                <label>Record</label>
            </value>
            <value>
                <fullName>object</fullName>
                <label>Object</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SCH_Schedule_Action__c/SCH_Schedule_Action__c.object-meta.xml
<CustomObject>
    <label>Schedule Action</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SCH_Schedule_Action__c/fields/Email_From_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_From_Address__c</fullName>
    <label>Email From Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/SCH_Schedule_Action__c/fields/Email_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Id__c</fullName>
    <label>Email Template Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/force-app/main/default/objects/SCH_Schedule_Action__c/fields/Email_To_Address_Field__c.field-meta.xml
<CustomField>
    <fullName>Email_To_Address_Field__c</fullName>
    <label>Email To Address Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCH_Schedule_Action__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <label>Schedule</label>
    <referenceTo>SCH_Schedule__c</referenceTo>
    <relationshipLabel>Schedule Actions</relationshipLabel>
    <relationshipName>Schedule_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SCH_Schedule_Action__c/fields/SMS_From_Number__c.field-meta.xml
<CustomField>
    <fullName>SMS_From_Number__c</fullName>
    <label>SMS From Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/force-app/main/default/objects/SCH_Schedule_Action__c/fields/SMS_Message__c.field-meta.xml
<CustomField>
    <fullName>SMS_Message__c</fullName>
    <label>SMS Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/force-app/main/default/classes/SCH_TestUtilities.cls
/**
 * Blackthorn.io, Inc CONFIDENTIAL
 * __________________________________
 * 
 *  [2022] Blackthorn.io, Inc
 *  All Rights Reserved.
 * 
 * NOTICE:  All information contained herein is, and remains
 * the property of Blackthorn.io, Inc and its suppliers,
 * if any. The intellectual and technical concepts contained
 * herein are proprietary to Blackthorn.io, Inc
 * and its suppliers and may be covered by U.S. and Foreign Patents,
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Blackthorn.io, Inc.
 *
 * 
 * A library of methods used as Test utility.
 *
 *
**/
@IsTest
global class SCH_TestUtilities {
    /*******************************************************************************************************
     * @description Method used to create Schedule Record
     **/
    public static SCH_Schedule__c createSchedule(String name, String baseObject, String relatedObject, boolean isInsert) {
        SCH_Schedule__c schedule = new SCH_Schedule__c();
        schedule.Name = name;
        schedule.Base_Object__c = baseObject;
        schedule.Related_Object__c = relatedObject;
        if (isInsert) {
            insert schedule;
        }
        return schedule;
    }
    /*******************************************************************************************************
     * @description Method used to create Schedule Record
     **/
    public static SCH_Schedule__c createSchedule(String name, String baseObject, String relatedObject, Map<String, String> baseFilter, Map<String, String> relatedFilter, Integer offsetValue, String offsetType, String offset, String status, boolean isInsert) {
        SCH_Schedule__c schedule = new SCH_Schedule__c();
        schedule.Name = name;
        schedule.Base_Object__c = baseObject;
        schedule.Related_Object__c = relatedObject;
        if (!baseFilter.isEmpty()) {
            String base_filter = '';
            if (baseFilter.get('filterOp') == 'contains') {
                base_filter = baseFilter.get('filterField') + ' like \'%' + baseFilter.get('filterValue') + '%\'';
            }
            schedule.Base_Object_Evaluate_Criteria__c = base_filter;
            schedule.Base_Object_Evaluate_Criteria_JSON__c = '{"logic_exp":"1","filters":[{"f_id":1,"f":"' + baseFilter.get('filterField') + '","op":"' + baseFilter.get('filterOp') + '","val":"' + baseFilter.get('filterValue') + '","f_type":"STRING","filter":"' + base_filter + '"}],"condition":"and"}';
        }
        if (!relatedFilter.isEmpty()) {
            String related_filter = '';
            if (relatedFilter.get('filterOp') == 'contains') {
                related_filter = relatedFilter.get('filterField') + ' like \'%' + relatedFilter.get('filterValue') + '%\'';
            }
            schedule.Related_Object_Evaluate_Criteria__c = related_filter;
            schedule.Related_Object_Evaluate_Criteria_JSON__c = '{"logic_exp":"1","filters":[{"f_id":1,"f":"' + relatedFilter.get('filterField') + '","op":"' + relatedFilter.get('filterOp') + '","val":"' + relatedFilter.get('filterValue') + '","f_type":"STRING","filter":"' + related_filter + '"}],"condition":"and"}';
        }

        schedule.Offset__c = offset;
        schedule.Offset_Type__c = offsetType;
        schedule.Offset_Value__c = offsetValue;
        schedule.Schedule_Date_Time_Field__c = 'CreatedDate';
        schedule.Status__c = status;
        schedule.Type__c = 'Object';
        if (isInsert) {
            insert schedule;
        }
        return schedule;
    }

    /*******************************************************************************************************
     * @description Method used to create Schedule Action Record
     **/
    public static SCH_Schedule_Action__c createScheduleEmailAction(String name, String emailFromAddress, String emailToAddress, String emailTemplateId, String scheduleId, boolean isInsert) {
        SCH_Schedule_Action__c scheduleAction = new SCH_Schedule_Action__c();
        scheduleAction.Name = name;
        scheduleAction.Schedule__c = scheduleId;
        scheduleAction.Action__c = 'Email';
        scheduleAction.Email_From_Address__c = emailFromAddress;
        scheduleAction.Email_To_Address_Field__c = emailToAddress;
        scheduleAction.Email_Template_Id__c = emailTemplateId;
        if (isInsert) {
            insert scheduleAction;
        }
        return scheduleAction;
    }

    /*******************************************************************************************************
     * @description Method used to create Schedule Action Record
     **/
    public static SCH_Schedule_Action__c createScheduleSMSAction(String name, String smsFromNumber, String smsToNumber, String smsmessage, String scheduleId, boolean isInsert) {
        SCH_Schedule_Action__c scheduleAction = new SCH_Schedule_Action__c();
        scheduleAction.Name = name;
        scheduleAction.Schedule__c = scheduleId;
        scheduleAction.Action__c = 'SMS';
        scheduleAction.SMS_From_Number__c = smsFromNumber;
        scheduleAction.SMS_Message__c = smsmessage;
        if (isInsert) {
            insert scheduleAction;
        }
        return scheduleAction;
    }

    /*******************************************************************************************************
     * @description Method used to create Email Template Record
     **/
    public static EmailTemplate createEmailTemplate(String name, String folderId, boolean isInsert) {
        EmailTemplate emailTemplate = new EmailTemplate();
        emailTemplate.Name = name;
        emailTemplate.isActive = true;
        emailTemplate.Name = name;
        emailTemplate.DeveloperName = name;
        emailTemplate.TemplateType = 'text';
        emailTemplate.FolderId = folderId;
        if (isInsert) {
            insert emailTemplate;
        }
        return emailTemplate;
    }

    /*******************************************************************************************************
     * @description Method used to create Account Record
     **/
    public static Account createAccount(String name, boolean isInsert) {
        Account acc = new Account();
        acc.Name = name;
        if (isInsert) {
            insert acc;
        }
        return acc;
    }

    /*******************************************************************************************************
     * @description Method used to create Contact Record
     **/
    public static Contact createContact(String name, String email, String accountId, boolean isInsert) {
        Contact con = new Contact();
        con.LastName = name;
        con.Email = email;
        con.AccountId = accountId;
        if (isInsert) {
            insert con;
        }
        return con;
    }

    /*******************************************************************************************************
     * @description Used to set dynamic mock response
     **/
    global class MockSingleRequest implements HttpCalloutMock {
        protected Integer code;
        protected String status;
        protected String method;
        protected String bodyAsString;
        protected Blob bodyAsBlob;
        protected Map<String, String> responseHeaders;

        public MockSingleRequest(Integer code, String status, String body, Map<String, String> responseHeaders) {
            this.code = code;
            this.status = status;
            method = null;
            this.bodyAsString = body;
            this.bodyAsBlob = null;
            this.responseHeaders = responseHeaders;
        }

        public void setMethod(String method) {
            this.method = method;
        }

        public String getMethod() {
            return method;
        }

        public HttpResponse respond(HttpRequest request) {
            HttpResponse response = new HttpResponse();
            response.setStatusCode(code);
            response.setStatus(status);
            if (bodyAsBlob != null)
                response.setBodyAsBlob(bodyAsBlob);
            else
                response.setBody(bodyAsString);
            System.debug(loggingLevel.WARN, bodyAsString);
            if (responseHeaders != null) {
                for (String key: responseHeaders.keySet()) {
                    response.setHeader(key, responseHeaders.get(key));
                }
            }
            return response;
        }
    }
}