force-app/main/default/objects/SCH_Schedule__c/SCH_Schedule__c.object-meta.xml
<CustomObject>
    <label>Schedule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/force-app/main/default/objects/SCH_Schedule__c/fields/Base_Object__c.field-meta.xml
<CustomField>
    <fullName>Base_Object__c</fullName>
    <label>Base Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/force-app/main/default/objects/SCH_Schedule__c/fields/Base_Object_Evaluate_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Base_Object_Evaluate_Criteria__c</fullName>
    <label>Base Object Evaluate Criteria</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/force-app/main/default/objects/SCH_Schedule__c/fields/Base_Object_Evaluate_Criteria_JSON__c.field-meta.xml
<CustomField>
    <fullName>Base_Object_Evaluate_Criteria_JSON__c</fullName>
    <label>Base Object Evaluate Criteria JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/force-app/main/default/objects/SCH_Schedule__c/fields/Execute_Now__c.field-meta.xml
<CustomField>
    <fullName>Execute_Now__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Execute Now</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SCH_Schedule__c/fields/Offset__c.field-meta.xml
<CustomField>
    <fullName>Offset__c</fullName>
    <label>Offset</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>before</fullName>
                <label>Before</label>
            </value>
            <value>
                <fullName>after</fullName>
                <label>After</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SCH_Schedule__c/fields/Offset_Type__c.field-meta.xml
<CustomField>
    <fullName>Offset_Type__c</fullName>
    <label>Offset Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>days</fullName>
                <label>Days</label>
            </value>
            <value>
                <fullName>hours</fullName>
                <label>Hours</label>
            </value>
            <value>
                <fullName>minutes</fullName>
                <label>Minutes</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SCH_Schedule__c/fields/Offset_Value__c.field-meta.xml
<CustomField>
    <fullName>Offset_Value__c</fullName>
    <label>Offset Value</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/force-app/main/default/objects/SCH_Schedule__c/fields/Related_Object_Evaluate_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Related_Object_Evaluate_Criteria__c</fullName>
    <label>Related Object Evaluate Criteria</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SCH_Schedule__c/fields/Related_Object_Evaluate_Criteria_JSON__c.field-meta.xml
<CustomField>
    <fullName>Related_Object_Evaluate_Criteria_JSON__c</fullName>
    <label>Related Object Evaluate Criteria JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/force-app/main/default/objects/SCH_Schedule__c/fields/Related_Object_Relationship_Name__c.field-meta.xml
<CustomField>
    <fullName>Related_Object_Relationship_Name__c</fullName>
    <label>Related Object Relationship Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCH_Schedule__c/fields/Schedule_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Date_Time__c</fullName>
    <label>Schedule Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/force-app/main/default/objects/SCH_Schedule__c/fields/Schedule_Date_Time_Field__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Date_Time_Field__c</fullName>
    <label>Schedule Date/Time Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/force-app/main/default/objects/SCH_Schedule__c/fields/SObject_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>SObject_Record_Id__c</fullName>
    <label>SObject Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/force-app/main/default/objects/SCH_Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>draft</fullName>
                <label>Draft</label>
            </value>
            <value>
                <fullName>processing</fullName>
                <label>Processing</label>
            </value>
            <value>
                <fullName>scheduled</fullName>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>completed</fullName>
                <label>Completed</label>
            </value>
            <value>
                <fullName>canceled</fullName>
                <label>Canceled</label>
            </value>
            <value>
                <fullName>failed</fullName>
                <label>Failed</label>
            </value>
            <value>
                <fullName>inactive</fullName>
                <label>Unschedule</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SCH_Schedule__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>record</fullName>
                <label>Record</label>
            </value>
            <value>
                <fullName>object</fullName>
                <label>Object</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SCH_Schedule_Action__c/SCH_Schedule_Action__c.object-meta.xml
<CustomObject>
    <label>Schedule Action</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SCH_Schedule_Action__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <label>Schedule</label>
    <referenceTo>SCH_Schedule__c</referenceTo>
    <relationshipLabel>Schedule Actions</relationshipLabel>
    <relationshipName>Schedule_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/force-app/main/default/classes/SCH_ScheduleSelector.cls
/**
 * Blackthorn.io, Inc CONFIDENTIAL
 * __________________________________
 * 
 *  [2022] Blackthorn.io, Inc
 *  All Rights Reserved.
 * 
 * NOTICE:  All information contained herein is, and remains
 * the property of Blackthorn.io, Inc and its suppliers,
 * if any. The intellectual and technical concepts contained
 * herein are proprietary to Blackthorn.io, Inc
 * and its suppliers and may be covered by U.S. and Foreign Patents,
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Blackthorn.io, Inc.
 *
 * 
 * The Selector class for the Schedule sObject
 *
**/
public with sharing class SCH_ScheduleSelector extends fflib_SObjectSelector {

	/**
	 *  @return a List of Schema.SObjectFields
	 *
	 *  Return a List of Schema.SObjectFields for this object.
	 *
	 **/
	public List<Schema.SObjectField> getSObjectFieldList() {
		return new List<Schema.SObjectField> {
			SCH_Schedule__c.Id,
			SCH_Schedule__c.Name,
			SCH_Schedule__c.Base_Object__c,
			SCH_Schedule__c.Base_Object_Evaluate_Criteria__c,
			SCH_Schedule__c.Base_Object_Evaluate_Criteria_JSON__c,
			SCH_Schedule__c.Related_Object__c,
			SCH_Schedule__c.Related_Object_Evaluate_Criteria__c,
			SCH_Schedule__c.Related_Object_Evaluate_Criteria_JSON__c,
			SCH_Schedule__c.Related_Object_Relationship_Name__c,
			SCH_Schedule__c.SObject_Record_Id__c,
			SCH_Schedule__c.Status__c,
			SCH_Schedule__c.Type__c,
			SCH_Schedule__c.Schedule_Date_Time__c,
			SCH_Schedule__c.Offset__c,
			SCH_Schedule__c.Offset_Type__c,
			SCH_Schedule__c.Offset_Value__c,
			SCH_Schedule__c.Schedule_Date_Time_Field__c,
			SCH_Schedule__c.Execute_Now__c
		};
	}

	/**
	 *  @return a Schema.SObjectType
	 *
	 *  Return the SObjectType for this object.
	 *
	 **/
	public Schema.SObjectType getSObjectType() {
		return SCH_Schedule__c.sObjectType;
	}

	/**
	 *  @param  ids - a Set of ids
	 *  @param  a List of Schedule
	 *
	 *
	 *
	 **/
	public List<SCH_Schedule__c> getSchedule(Set<Id> ids) {
		assertIsAccessible();
		fflib_QueryFactory query = newQueryFactory();
		query.setCondition('Id IN :ids');
		System.debug(loggingLevel.WARN, 'QUERY: ' + query.toSOQL());
		return (List<SCH_Schedule__c> ) Database.query(query.toSOQL());
	}

	/**
	 *  @param  ids - a Set of ids
	 *  @param  a List of Schedule with Schedule Actions
	 *
	 *
	 *
	 **/
	public List<SCH_Schedule__c> getScheduleWithActions(Set<Id> ids) {
		assertIsAccessible();
		fflib_QueryFactory query = newQueryFactory();
		query.setCondition('Id IN :ids');
		new SCH_ScheduleActionSelector()
			.addQueryFactorySubselect(query, SCH_BtBaseUtils.nameSpacePreFix + 'Schedule_Actions__r');
		System.debug(loggingLevel.WARN, 'QUERY: ' + query.toSOQL());
		return (List<SCH_Schedule__c> ) Database.query(query.toSOQL());
	}

	public String buildSObjectSchedulesByStatusQuery(String sObjectName, List<String> statusList) {
		assertIsAccessible();
		String query = String.format(
			'SELECT {0} FROM {1} ',
			new List<String> {
				getFieldListString(),
				getSObjectName(),
				sObjectName
			}
		);
		if (sObjectName != null) {
			query += ' WHERE Base_Object__c = :sObjectName';
		}
		if (statusList != null && statusList.size() > 0) {
			query += ' AND Status__c IN :statusList';
		}
		query += ' ORDER BY Name';
		System.debug('QUERY: ' + query);
		return query;
	}

}